### PR TITLE
Timer Panel - Timer Actions for Enable and Interval

### PR DESCRIPTION
**Pull request by BlueFinBima**
PR is to allow review of the change to the Timer Panel described below (https://github.com/HeliosVirtualCockpit/Helios/pull/612/commits/f1683824a0c7ed65e794f7c9c159d4099d953734)

Creates Action to Enable / Disable the timer function and also an action to set the timer interval.  When the panel is un-hidden, the interval is always set to the value configured for the Timer Panel in PE to ensure the repeatability of activity on the timer panel.  To allow a profile to have an interval while having the timer disabled by default, the conditional collapse in the behaviour for the interval value has been disabled because it is not intuitive to enable the timer, set a value and see the interval disappear when the timer is disabled. 

Use Case:  A timer panel is made visible with a control for the landing gear handle on it, expecting that it might be interacted with, and a long time interval would be configured for the panel so that it would eventually hide if the user ignores it and does not lower the Landing gear.  If the user drops the landing gear, then there is the possibility that the gear might be retracted again so the panel is not hidden immediately, but a shorter interval is set for the panel to give the pilot a chance to confirm the gear is down, but if no more input for the new shorter period, the panel will hide itself.  There could also be a button on the panel for the user to disable the timer so that it does not auto hide.

### CODE REVIEW

**Comment by BlueFinBima** [comment]
@Todd1215 Would you be willing to review this change to your Timer Panel?  Everything seems to work as I intended, but it is always useful to have a second pair of eyes on this, especially since I guess you're already using the Timer Panel and I don't want to regress anything.

**Comment by linknetx** [comment]
This is obviously configured for a specific purpose which appears to be to reset the timer interval with the Timer Panel unhidden, which if you were starting with the Timer Panel hidden would be **after** unhiding the Timer Panel. However looking at it from a more general point of view and seeing that item in the Toolbox I would have expected to to be able to set a new timer interval **before** unhiding the Timer Panel. But unfortunately that doesn't work since unhiding the Timer Panel always reverts to the time interval set in the Profile Editor. By the way the legacy mode of operation works exactly as before during testing.

**Comment by BlueFinBima** [comment]
Thanks for the comments @linknetx, and for the testing .  I agree that confusion is still there  You are correct that the use case I envisaged was for unhidden interaction.  The design question is really about the relationship between the interval defined in Profile Editor and the interval set by the action.  Maybe the correct design should be to reset the interval to the one defined in profile editor each time the panel is hidden rather than when the panel is unhidden.   Does that seem a more intuitive approach?

**Comment by linknetx** [comment]
Perhaps just changing the wording of the binding would make it less confusing and clearer:

**Comment by BlueFinBima** [comment]
@linknetx & @Todd1215 thanks both for the thoughts and comments.  The PR now represents a redesign with two interval actions - one to set the default interval and another to set a "one-time" interval.  I've also updated the descriptions of the input bindings.  Hopefully this will reduce potential confusion.

**Comment by linknetx** [comment]
@BlueFinBima This is me now just being pedantic "The timer then returns to the **deault** interval." :)

**Comment by BlueFinBima** [comment]
Thanks for the input gents.  Much appreciated.

**Pull request merged**
