### PR TITLE
Ka-50: Fixed collimator borders clipping of HUD

### PR DESCRIPTION
**Pull request by Lord-Mustang**
## Summary
Fixed clipping by the collimator borders on the Ka-50's HUD by adjusting the render position of the HUD-only viewport.

## Version
Patch generated on 002_007_00017_29493_00000 Steam openbeta.

I checked it within patchset 002_007_00016_28111_00000, the latest set at the time of writing, on version 002_007_00017_29493_00000. Please check on version 002_007_00016_28111_00000 if compatibility is required with it. I don't have this game version.

## Detailed
A small patch that changes/fixes the render position of the Ka-50's HUD.

The exported viewport renders the HUD from an incorrect Y-coordinate. Since the collimator borders define the render limits of the HUD, a part of it will be cut off/clipped.

Here is a visualisation of this clipping. The collimator area is coloured purple.
<details>
  <p>

image

  </p>
</details>

Here is a visualisation with the new patch.
<details>
  <p>

image

  </p>
</details>

Purple debug rendering is not included in the patch, for clarity's sake.

### CODE REVIEW

**Comment by BlueFinBima** [comment]
Hi @Lord-Mustang thanks for the PR.  Can you please attach a screen shot of the **in-game** HUD with and without the patch so that I can verify that the change of value `{sy_l = 0.0499138832}` to `{sy_l = 0.0}` does not impact in-game operation?  Unfortunately I don't have the Ka-50 module to do this myself.

**Comment by BlueFinBima** [comment]
I've pre-emptively added commits for this patch to allow it to go out with other patch changes due to ship on Monday.  I realise that this change is supposed to be a HUD-Only viewport, but I would still like visual confirmation that the in-game HUD remains unchanged before shipment.

**Comment by Lord-Mustang** [comment]
@BlueFinBima Here are complete screenshots including the game viewport:

With patch applied:
<details>
  <p>

image

  </p>
</details>

Without patch applied:
<details>
  <p>

image

  </p>
</details>

**Comment by BlueFinBima** [comment]
Many thanks for the screen shots.

**Comment by BlueFinBima** [comment]
This patch was built as a package with M-2000C patch changes as per the above mentioned commits.   Now shipped in https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.5308.1
@Lord-Mustang many thanks for this contribution to the project.

**Pull request closed without merging**
