### PR TITLE
alternative fix for issue 486

### PR DESCRIPTION
**Pull request by derammo**
this restores the ability to assign explicit IDs to triggers, values, and actions

### CODE REVIEW

**Comment by BlueFinBima** [comment]
Hi Ammo,  glad to see that you're still keeping an eye on Helios.  Clearly not my intention to break the DCS-BIOS interfaces.  Anyway, this fix looks good for the binding performed in the deserializer.  
Unfortunately, Auto Binding of **actions** in CompositeVisual seems problematic (the following is an example).  Triggers and Values seem fine.
```
2021-11-12 14:26:22.1142|DEBUG|GadrocsWorkshop.Helios.CompositeVisual|Auto binding child SMC Device
2021-11-12 14:26:22.1142|ERROR|GadrocsWorkshop.Helios.CompositeVisual|Cannot find action set.SMC_Fuze Mode 
```

**Comment by BlueFinBima** [comment]
The actions which seem to have problems autobinding are those for gauges embedded in other gauges.  Test case was to add the AV-8B interface, and then drag the absurd "Front Cockpit" from the AV-8B Gauge toolbox onto the monitor.

**Comment by derammo** [comment]
ok do you want me to fix the pre-existing problem in the master after we approve this PR?

I mainly don't have the setup right now to actually run DCS and validate the profiles work correctly.  That's why I wanted you to make sure this change makes your profile work at least as well as 1.6.3xxx did.   Hence the PR.

**Comment by derammo** [comment]
and I actually unsubscribed from Helios repos, but I forgot to unsubscribe yours :)  so that is why I was notified.   If something like this happens in the future where some of my extensive changes in 1.6.5 break core functionality, totally reach out directly on Discord.   I am available for developers forever, most likely.   Just don't want the support issues ringing my phone any more :)

**Comment by BlueFinBima** [comment]
Good to understand the communication protocol, and thanks.  I was trying not to bug you.
The existing problem with the action could be a bug in the AV-8B front cockpit, so I wouldn't waste your time on it since nobody else has reported it.   
Similarly, the EnumConverter debug message might have been around for a while so I can't get excited about it.  
I just want to do a little more testing with my own FA-18C profile and then I'll click the button.

**Comment by derammo** [comment]
I have seen a lot of the EnumConverter messages and they just mean that the XAML binding that has the converter attached to it is currently not bound or bound to null (could be the object hasn't been loaded yet or does not apply right now).   This happens in the UI XAML for combo boxes.  

I don't know if I added the message and that's why you are just seeing it now, but I always ignore them as a "maybe check in the future if the bindings/XAML/UI-design can be improved"

**Comment by derammo** [comment]
in terms of next steps on this bug, I guess if you could validate that this branch works for you, then you can approve it and it can go to master?

**Comment by derammo** [comment]
(removed question you already answered)

**Review by BlueFinBima — APPROVED** [review]
Thanks for averting another regression.  Much appreciated.  As far as I can tell, this addresses #486

**Pull request merged**
