### PR TITLE
Changes to help diagnose DirectX problems

### PR DESCRIPTION
**Pull request by BlueFinBima**
#485 protection and additional diagnostics for this issue which seems to be a slider issue.
#491 and #659 seem to be the same problem and again this PR is to add protection and provide extra diagnostic messages.  
@Todd1215 fancy reviewing this for me?

### CODE REVIEW

**Comment by BlueFinBima** [comment]
Couple of worries from my perspective. 
1. I can't test this because all of my DirectX devices behave themselves
2. Will anyone notice there is a problems when it happens?
3. Will the log messages be enough to move the diagnosis of the two issues?

**Review by Todd1215 — COMMENTED** [review]
Not sure it will get us any closer to resolving unless we can reproduce the problem but the additional state checks and logging can't hurt.

**Review by Todd1215 — COMMENTED** [review]
Hopefully the value checks before use will prevent any further errors

**Review by Todd1215 — COMMENTED** [review]
The additional logging can't hurt.

**Comment by BlueFinBima** [comment]
Thanks @Todd1215 , I appreciate the input.  My gut feel is that the AddFunction problem is due to bad firmware in the devices - possibly causing duplicate instance GUIDs -  and although these devices are relatively cheap, there is also no guarantee that if I bought one, it would have the problematic firmware.  The Slider problem I'm thinking is due to bad firmware again, or possibly a bug in the combining software that companies like WinWing and Thrustmaster use.  All supposition.
Option 1 (which the code in the PR at the moment) is to effectively ignore the bad behaviour and hope that the vendors fix the problems on their own.  Option 2 is to be more aggressive in Helios, which would involve throwing an exception so the user sits up and notices, and then recreates the problem with debug on.  My guess is that if you have the problem, it'll be easily reproduceable.  If we go the Option 2 route, then there is still a good chance that Helios would be unable to fix the problem.
So my conclusion is that we continue with option 1 and decide on the next step,  when there is **a little** more information  to go on.

**Comment by ereidelbach** [comment]
Apologies for the delayed response, but in regards to your question in #491, I was using two identical zero-delay boards plugged into an external USB hub.

I know there are a wide variety of these boards so accounting for them all is likely not possible, but here are the ones I'm using:
https://www.amazon.com/gp/product/B081NMXS16

I'm a little out of date with the latest version of Helios but I'll make a note to update and test the boards later this week. Not sure if it will be helpful, but at least I can provide more feedback. I've since moved away from these boards to more robust USB devices (e.g. Leo Bodnar boards) or Stream Decks and haven't had any issues since then.

**Pull request merged**
