### PR TITLE
Ka-50 III / Black Shark 3 viewports and patches

### PR DESCRIPTION
**Pull request by Lord-Mustang**
Added viewports and their corresponding patches for the Ka-50 III.

<details>
  <summary>Screenshot</summary>
  

</details>

### CODE REVIEW

**Comment by BlueFinBima** [comment]
Hi @Lord-Mustang, thanks a lot for the PR.
Thanks for the screenshots showing that you've tested the viewports.

1.  Because we use GIT to build the viewport set, can you provide me with the four patched and four unpatched files?  Without these I will not be able to build a patch set in future.
1.  Did you create the patches manually or did you use the GeneratePatches tool?
1. In the template, you refer to the module as "KA-50-3" but I understood that the module was "KA-50_3".  Can you confirm which is correct?
1. You've named the template for 16:9, but the presumption is 1:1 pixel.  Why is the template only applicable to a screen ratio of 16:9?

**Comment by Lord-Mustang** [comment]
> Because we use GIT to build the viewport set, can you provide me with the four patched and four unpatched files? Without these I will not be able to build a patch set in future.

Sent in private
> Did you create the patches manually or did you use the GeneratePatches tool?

Using the GeneratePatches tool. The patches for all the other aircraft are the same as the previous patch set you generated, I didn't edit them. They are copied from set 002_008_00000_33006_00000, which are the current patches as of date.

> In the template, you refer to the module as "KA-50-3" but I understood that the module was "KA-50_3". Can you confirm which is correct?

Corrected in [`d9e6dfe` (#687)](https://github.com/HeliosVirtualCockpit/Helios/pull/687/commits/d9e6dfe99e73c5b05f48e13fac1ec169b05130db)

> You've named the template for 16:9, but the presumption is 1:1 pixel. Why is the template only applicable to a screen ratio of 16:9?

I don't know. I copied this from the Ka-50's viewports (for consistenency), given that their dimensions are the same. There are a few sets of viewport templates that use this naming. If it isn't desired, it should probably be removed from at least the Ka-50, Ka-50_3 and possibly a few other viewport templates.

**Comment by BlueFinBima** [comment]
@Lord-Mustang Thanks for the answers.  The 16:9 text does not seem to make it into the outside world.   Maybe someone thought that the location in the final template was relevant, but I'm pretty sure that it is ignored.

**Comment by Lord-Mustang** [comment]
@BlueFinBima Yes, it isn't reflected in the UI, so I'm not sure what purpose it serves.

**Pull request merged**
